# The URL the site will be built for
base_url = "https://uutils.github.io"

title = "uutils"

description = "uutils — cross-platform Rust reimplementations of essential Unix command-line utilities"

default_language = "en"

generate_feeds = true

[markdown]
[markdown.highlighting]
style = "class"
light_theme = "one-light"
dark_theme = "one-dark-pro"
